/**
 * @file i2s_config.h
 * @date 2021-01-08
 *
 * NOTE:
 * This file is generated by DAVE-4. Any manual modification done to this file will be lost when the code is
 * regenerated.
 *
 * @cond
 ***********************************************************************************************************************
 * I2S_CONFIG v4.0.6 - Configures a USIC channel to perform transmit & receive operations using I2S protocol.
 *
 * Copyright (c) 2015-2020, Infineon Technologies AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,are permitted provided that the
 * following conditions are met:
 *
 *   Redistributions of source code must retain the above copyright notice, this list of conditions and the  following
 *   disclaimer.
 *
 *   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
 *   disclaimer in the documentation and/or other materials provided with the distribution.
 *
 *   Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote
 *   products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT  OF THE
 * USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * To improve the quality of the software, users are encouraged to share modifications, enhancements or bug fixes
 * with Infineon Technologies AG (dave@infineon.com).
 ***********************************************************************************************************************
 *
 * Change History
 * --------------
 *
 * 2016-05-30:
 *     - Initial version for DAVEv4
 *
 * 2021-01-08:
 *     - Modified check for minimum XMCLib version
 *
 * @endcond
 *
 */
/***********************************************************************************************************************
 * HEADER FILES
 **********************************************************************************************************************/
#ifndef I2S_CONFIG_H
#define I2S_CONFIG_H

#include "xmc_i2s.h"
#include "DAVE_common.h"
#include "i2s_config_conf.h"

/***********************************************************************************************************************
 * MACROS
 **********************************************************************************************************************/
#define I2S_CONFIG_XMC_LIB_MAJOR_VERSION 2
#define I2S_CONFIG_XMC_LIB_MINOR_VERSION 1
#define I2S_CONFIG_XMC_LIB_PATCH_VERSION 2

#if !((XMC_LIB_MAJOR_VERSION > I2S_CONFIG_XMC_LIB_MAJOR_VERSION) ||\
      ((XMC_LIB_MAJOR_VERSION == I2S_CONFIG_XMC_LIB_MAJOR_VERSION) && (XMC_LIB_MINOR_VERSION > I2S_CONFIG_XMC_LIB_MINOR_VERSION)) ||\
      ((XMC_LIB_MAJOR_VERSION == I2S_CONFIG_XMC_LIB_MAJOR_VERSION) && (XMC_LIB_MINOR_VERSION == I2S_CONFIG_XMC_LIB_MINOR_VERSION) && (XMC_LIB_PATCH_VERSION >= I2S_CONFIG_XMC_LIB_PATCH_VERSION)))
#error "I2S_CONFIG requires XMC Peripheral Library v2.1.2 or higher"
#endif

/***********************************************************************************************************************
 * ENUMS
 **********************************************************************************************************************/

/**
 * @ingroup I2S_CONFIG_enumerations
 * @{
 */

/**
 * @brief Enum to describe the possible status values, returned
 *  by I2S_CONFIG APIs.
 */
typedef enum I2S_CONFIG_STATUS
{
  I2S_CONFIG_STATUS_SUCCESS = 0U,        /**< APP initialization is success */
  I2S_CONFIG_STATUS_FAILURE = 1U         /**< APP initialization is failure */
} I2S_CONFIG_STATUS_t;

/**
 * @}
 */

/***********************************************************************************************************************
 * DATA STRUCTURES
 **********************************************************************************************************************/

typedef void (*I2S_CONFIG_func_ptr) (void);

/**
 * @ingroup I2S_CONFIG_datastructures
 * @{
 */

/**
 * @brief Structure for holding the configuration parameters of the I2S channel.
 */
typedef struct I2S_CONFIG_CONF
{
  const XMC_I2S_CH_CONFIG_t *const channel_config;    /**< Reference to I2S configuration structure */
  I2S_CONFIG_func_ptr const i2s_config_init_func;           /**< Function pointer to configure a USIC channel for I2S */
} I2S_CONFIG_CONF_t;

/**
 * @brief Handler structure with pointers to static parameters.
 */
typedef struct I2S_CONFIG
{
  XMC_USIC_CH_t *const channel;                  /**< USIC channel */
  const I2S_CONFIG_CONF_t *const config;         /**< I2S_CONFIG configuration structure pointer */
} I2S_CONFIG_t;

/**
 * @}
 */

#ifdef __cplusplus
extern "C" {
#endif
/***********************************************************************************************************************
 * API Prototypes
 **********************************************************************************************************************/
/**
 * @ingroup I2S_CONFIG_apidoc
 * @{
 */

/**
 * @brief Get the I2S_CONFIG APP version.
 * @return DAVE_APP_VERSION_t APP version information (major, minor and patch number)
 *
 * Example Usage:
 *
 * @code
 *   #include "DAVE.h"
 *
 *   int main(void)
 *   {
 *     I2S_CONFIG_STATUS_t init_status;
 *     DAVE_APP_VERSION_t i2s_config_version;
 *     uint8_t valid_str[] = "I2S_CONFIG APP supported!";
 *
 *     init_status = (I2S_CONFIG_STATUS_t)I2S_CONFIG_Init(&I2S_CONFIG_0);
 *     if(init_status == I2S_CONFIG_STATUS_SUCCESS)
 *     {
 *       i2s_config_version = I2S_CONFIG_GetAppVersion();
 *       if (i2s_config_version.major != 4U) {
 *       // Probably, not the right version.
 *       }
 *
 *       // More code here
 *       while(1) {
 *
 *       }
 *     }
 *     else
 *     {
 *      XMC_DEBUG("main: Application initialization failed");
 *      while(1U)
 *      {
 *      }
 *     }
 *      return (1U);
 *  }
 *  @endcode
 */
DAVE_APP_VERSION_t I2S_CONFIG_GetAppVersion(void);

/**
 * @brief Function to initialize the I2S module as per the configuration made
 * in GUI.
 * @param handle Pointer to static content of APP configuration.
 * @return I2S_CONFIG_STATUS_t: Status of the I2S driver initialization.\n
 *   @ref I2S_CONFIG_STATUS_SUCCESS - on successful initialization.\n
 *   @ref I2S_CONFIG_STATUS_FAILURE - if initialization fails.\n
 *
 * \par<b>Description:</b><br>
 * This function configures USIC registers based on the settings provided in the GUI.
 * <BR>
 *
 * Example Usage:
 * @code
 *   #include "DAVE.h"   // Declarations from DAVE Code Generation (includes SFR declaration)
 *
 *   int main(void)
 *   {
 *     I2S_CONFIG_STATUS_t init_status;
 *
 *     init_status = (I2S_CONFIG_STATUS_t)I2S_CONFIG_Init(&I2S_CONFIG_0);
 *     if(init_status == I2S_CONFIG_STATUS_SUCCESS)
 *     {
 *         while(1U)
 *         {
 *         }
 *     }
 *     else
 *     {
 *      XMC_DEBUG("main: Application initialization failed");
 *      while(1U)
 *      {
 *      }
 *     }
 *      return (1U);
 *  }
 *  @endcode
 */
I2S_CONFIG_STATUS_t I2S_CONFIG_Init(const I2S_CONFIG_t *const handle);


/**
 * @}
 */

/* Include APP extern declaration file */
#include "i2s_config_extern.h"

#ifdef __cplusplus
}
#endif

#endif /* I2S_CONFIG_H */
